import { randomUUID } from 'node:crypto'
import type pg from 'pg'
import { syncCustomerBillPreferencePatch } from '../../bill-settings.js'
import type { ServerRepository } from '../../http-types.js'
type Customer = Awaited<ReturnType<NonNullable<ServerRepository['listCustomers']>>>[number]
type Supplier = Awaited<ReturnType<NonNullable<ServerRepository['listSuppliers']>>>[number]
type Group = NonNullable<Customer['customer_group']>
export function createCustomerCrudRepository(pool: pg.Pool, deps: { ensureTables: (pool: pg.Pool) => Promise<void>; nextCode: (pool: pg.Pool, organizationId: string) => Promise<string>; findGroup: (pool: pg.Pool, organizationId: string, groupId: string) => Promise<Group | null>; hydrate: (customer: Customer, suppliers: Supplier[]) => Customer }): Pick<ServerRepository, 'createCustomer' | 'findCustomerByCode' | 'updateCustomer'> {
 return {
  async createCustomer(input) { await deps.ensureTables(pool); const code=input.code?.trim()||await deps.nextCode(pool,input.organizationId),groupId=input.customer_group_id??null,group=groupId?await deps.findGroup(pool,input.organizationId,groupId):null,createdAt=new Date().toISOString();const data:Customer={id:randomUUID(),code,name:input.name.trim(),phone:input.phone?.trim()||null,tax_code:input.tax_code?.trim()||null,address:input.address?.trim()||null,customer_group_id:groupId,customer_group:group,created_by:input.created_by??null,created_at:createdAt,total_sales_amount:0,total_debt_amount:0,customer_type:input.customer_type?.trim()||null,company_name:input.company_name?.trim()||null,area_name:null,ward_name:null,note:input.note?.trim()||null,source_creator_name:null,last_transaction_at:null,kiotviet_current_debt:null,kiotviet_net_sales:null,status:'active'};await pool.query(`insert into customer_snapshots (id, organization_id, code, data, source_type, created_at, updated_at) values ($1,$2,$3,$4::jsonb,'manual',$5::timestamptz,now())`,[data.id,input.organizationId,data.code,JSON.stringify(data),data.created_at]);return deps.hydrate(data,[]) },
  async findCustomerByCode(input) { await deps.ensureTables(pool);const [customers,suppliers]=await Promise.all([pool.query('select data from customer_snapshots where organization_id=$1 and lower(code)=lower($2) limit 1',[input.organizationId,input.code]),pool.query('select data from supplier_snapshots where organization_id=$1',[input.organizationId])]);const customer=customers.rows[0]?.data as Customer|undefined;return customer?deps.hydrate(customer,suppliers.rows.map(r=>r.data as Supplier)):null },
  async updateCustomer(input) { await deps.ensureTables(pool);const existing=await pool.query('select data from customer_snapshots where organization_id=$1 and (id=$2 or lower(code)=lower($2)) limit 1',[input.organizationId,input.id]);const current=existing.rows[0]?.data as Customer|undefined;if(!current)return null;if(current.code.trim().toLowerCase()==='khachle'&&(input.patch.preferred_bill_template!==undefined||input.patch.preferred_bill_templates!==undefined))throw Object.assign(new Error('WALK_IN_BILL_PREFERENCE_FORBIDDEN'),{code:'WALK_IN_BILL_PREFERENCE_FORBIDDEN'});const group=input.patch.customer_group_id===undefined?current.customer_group:input.patch.customer_group_id===null?null:await deps.findGroup(pool,input.organizationId,input.patch.customer_group_id);const preference=input.patch.preferred_bill_template!==undefined||input.patch.preferred_bill_templates!==undefined?syncCustomerBillPreferencePatch({preferred_bill_template:input.patch.preferred_bill_template,preferred_bill_templates:input.patch.preferred_bill_templates,currentTemplate:current.preferred_bill_template??null,currentTemplates:current.preferred_bill_templates??null}):null;const data:Customer={...current,code:input.patch.code??current.code,name:input.patch.name??current.name,phone:input.patch.phone===undefined?current.phone:input.patch.phone,tax_code:input.patch.tax_code===undefined?current.tax_code:input.patch.tax_code,address:input.patch.address===undefined?current.address:input.patch.address,note:input.patch.note===undefined?current.note:input.patch.note,customer_group_id:input.patch.customer_group_id===undefined?current.customer_group_id:input.patch.customer_group_id,customer_group:group,customer_type:input.patch.customer_type===undefined?current.customer_type:input.patch.customer_type,company_name:input.patch.company_name===undefined?current.company_name:input.patch.company_name,preferred_bill_template:preference?preference.preferred_bill_template:current.preferred_bill_template??null,preferred_bill_templates:preference?preference.preferred_bill_templates:current.preferred_bill_templates??null};await pool.query('update customer_snapshots set code=$3,data=$4::jsonb,updated_at=now() where organization_id=$1 and id=$2',[input.organizationId,current.id,data.code,JSON.stringify(data)]);return deps.hydrate(data,[]) },
 }
}
