import { randomUUID } from 'node:crypto'
import type pg from 'pg'
import type { ServerRepository } from '../../http-types.js'
type Supplier=Awaited<ReturnType<NonNullable<ServerRepository['listSuppliers']>>>[number]
type Customer=Awaited<ReturnType<NonNullable<ServerRepository['listCustomers']>>>[number]
type ListInput=Parameters<NonNullable<ServerRepository['listSuppliers']>>[0]
export function createSupplierCrudRepository(pool:pg.Pool,deps:{ensureTables:(pool:pg.Pool)=>Promise<void>;recompute:(pool:pg.Pool,organizationId:string)=>Promise<void>;matches:(url:URL,supplier:Supplier)=>boolean;rank:(input:{pool:pg.Pool;organizationId:string;userId?:string;entityType:'supplier';url:URL;items:Supplier[];codeOf:(item:Supplier)=>string;nameOf:(item:Supplier)=>string})=>Promise<Supplier[]>;nextCode:(pool:pg.Pool,organizationId:string)=>Promise<string>}):Pick<ServerRepository,'listSuppliers'|'createSupplier'|'updateSupplier'>{return{
 async listSuppliers(input:ListInput){await deps.ensureTables(pool);await deps.recompute(pool,input.organizationId);const result=await pool.query(`select data from supplier_snapshots where organization_id=$1 order by coalesce(nullif(data->>'created_at','')::timestamptz,created_at) desc`,[input.organizationId]);const items=result.rows.map(r=>r.data as Supplier).filter(s=>deps.matches(input.url,s));return deps.rank({pool,organizationId:input.organizationId,userId:input.userId,entityType:'supplier',url:input.url,items,codeOf:s=>s.code,nameOf:s=>s.name})},
 async createSupplier(input){await deps.ensureTables(pool);const code=input.code?.trim()||await deps.nextCode(pool,input.organizationId),existing=await pool.query('select id from supplier_snapshots where organization_id=$1 and lower(code)=lower($2) limit 1',[input.organizationId,code]);if(existing.rows[0])throw new Error('SUPPLIER_ALREADY_EXISTS');const linkedCustomerId=input.linked_customer_id?.trim()||null;let linkedCustomer:{id:string;code:string;name:string}|null=null;if(linkedCustomerId){const result=await pool.query('select data from customer_snapshots where organization_id=$1 and id=$2 limit 1',[input.organizationId,linkedCustomerId]),customer=result.rows[0]?.data as Customer|undefined;if(!customer)throw new Error('LINKED_CUSTOMER_NOT_FOUND');linkedCustomer={id:customer.id,code:customer.code,name:customer.name}}const createdAt=new Date().toISOString(),data:Supplier={id:randomUUID(),code,name:input.name.trim(),phone:input.phone?.trim()||null,email:input.email?.trim()||null,address:input.address?.trim()||null,tax_code:input.tax_code?.trim()||null,linked_customer_id:linkedCustomerId,linked_customer:linkedCustomer,notes:input.notes?.trim()||null,status:input.status?.trim()||'active',current_payable_amount:0,total_purchase_amount:0,created_at:createdAt,source_creator_name:null,source_created_at:null,company_name:null};try{await pool.query(`insert into supplier_snapshots (id,organization_id,code,data,source_type,created_at,updated_at) values ($1,$2,$3,$4::jsonb,'manual',$5::timestamptz,now())`,[data.id,input.organizationId,data.code,JSON.stringify(data),data.created_at])}catch(error){if(isUnique(error))throw new Error('SUPPLIER_ALREADY_EXISTS');throw error}return data},
 async updateSupplier(input){await deps.ensureTables(pool);const existing=await pool.query('select data from supplier_snapshots where organization_id=$1 and id=$2 limit 1',[input.organizationId,input.id]),current=existing.rows[0]?.data as Supplier|undefined;if(!current)return null;const linkedCustomerId=input.patch.linked_customer_id!==undefined?input.patch.linked_customer_id:current.linked_customer_id??null,linked=linkedCustomerId?await pool.query('select data from customer_snapshots where organization_id=$1 and id=$2 limit 1',[input.organizationId,linkedCustomerId]):null,customer=linked?.rows[0]?.data as Customer|undefined;const data:Supplier={...current,code:input.patch.code??current.code,name:input.patch.name??current.name,phone:input.patch.phone??current.phone,email:input.patch.email??current.email,address:input.patch.address??current.address,tax_code:input.patch.tax_code??current.tax_code,linked_customer_id:linkedCustomerId,linked_customer:customer?{id:customer.id,code:customer.code,name:customer.name}:null,notes:input.patch.notes??current.notes,status:input.patch.status??current.status};await pool.query('update supplier_snapshots set code=$3,data=$4::jsonb,updated_at=now() where organization_id=$1 and id=$2',[input.organizationId,input.id,data.code,JSON.stringify(data)]);return data},
}}
function isUnique(error:unknown){return typeof error==='object'&&error!==null&&'code'in error&&error.code==='23505'}
