import type pg from 'pg'
import type { ServerRepository } from '../../http-types.js'
type Supplier = Awaited<ReturnType<NonNullable<ServerRepository['listSuppliers']>>>[number]
type Customer = Awaited<ReturnType<NonNullable<ServerRepository['listCustomers']>>>[number]
export function createSupplierImportRepository(pool: pg.Pool, deps: { ensureTables: (pool: pg.Pool) => Promise<void>; hashText: (value: string) => string }): Pick<ServerRepository, 'findSuppliersByCodes' | 'upsertSuppliersByCode' | 'deleteImportedKiotVietSuppliers'> {
 return {
  async findSuppliersByCodes(input){await deps.ensureTables(pool);const result=await pool.query(`select requested.code from unnest($2::text[]) as requested(code) where exists (select 1 from supplier_snapshots s where s.organization_id=$1 and lower(s.code)=lower(requested.code))`,[input.organizationId,input.codes]);return new Set(result.rows.map(row=>String(row.code)))},
  async upsertSuppliersByCode(input){await deps.ensureTables(pool);let created=0,updated=0;for(const row of input.rows){const existing=await pool.query('select data from supplier_snapshots where organization_id=$1 and code=$2 limit 1',[input.organizationId,row.code]),current=existing.rows[0]?.data as Supplier|undefined,matching=await pool.query(`select data from customer_snapshots where organization_id=$1 and (lower(code)=lower($2) or lower(name)=lower($3)) limit 1`,[input.organizationId,row.code,row.name]),customer=matching.rows[0]?.data as Customer|undefined;const data:Supplier={id:current?.id??`supplier-kv-${deps.hashText(row.code)}`,code:row.code,name:row.name,phone:row.phone,email:row.email,address:row.address,tax_code:row.tax_code,linked_customer_id:current?.linked_customer_id??customer?.id??null,linked_customer:current?.linked_customer??(customer?{id:customer.id,code:customer.code,name:customer.name}:null),notes:row.note,status:row.status,current_payable_amount:row.kiotviet_current_payable??current?.current_payable_amount??0,total_purchase_amount:row.kiotviet_total_purchase??current?.total_purchase_amount??0,created_at:row.source_created_at??current?.created_at??new Date().toISOString(),source_creator_name:row.source_creator_name,source_created_at:row.source_created_at,company_name:row.company_name};const result=await pool.query(`insert into supplier_snapshots (id,organization_id,code,data,source_type,created_at,updated_at) values ($1,$2,$3,$4::jsonb,'kiotviet_import',coalesce($5::timestamptz,now()),now()) on conflict (organization_id,code) do update set data=excluded.data,source_type=excluded.source_type,updated_at=now() returning (xmax=0) as inserted`,[data.id,input.organizationId,data.code,JSON.stringify(data),data.created_at]);if(result.rows[0]?.inserted)created++;else updated++}return{created,updated,skipped:0}},
  async deleteImportedKiotVietSuppliers(input){await deps.ensureTables(pool);const result=await pool.query(`delete from supplier_snapshots where organization_id=$1 and source_type='kiotviet_import'`,[input.organizationId]);return{deleted:result.rowCount??0,blocked:0}},
 }
}
