import type { CurrentUserData, CustomerDebtDetailData, ServerRepository } from '../../http-types.js'
import type { RouteResult } from '../../route-types.js'
import type { CustomerOpenDebtInvoiceInput } from './customer-debt.js'
interface Dependencies { currentUser:CurrentUserData; repository:ServerRepository; url:URL; page:number; pageSize:number; getCustomerId:(path:string)=>string; path:string; paged:<T>(items:T[],page:number,size:number)=>unknown; fallbackList:()=>unknown[]; fallbackDetail:(id:string)=>CustomerDebtDetailData; sliceOpen:(invoices:CustomerOpenDebtInvoiceInput[],options:{amount?:number;limit:number})=>unknown }
export function createFinanceDebtQueryHandlers(d:Dependencies):{listCustomerDebts:()=>RouteResult;getCustomerDebt:()=>RouteResult;getCustomerOpenDebts:()=>RouteResult}{return {
 listCustomerDebts:async()=>{if(d.repository.listCustomerDebts)return {found:true,data:d.paged(await d.repository.listCustomerDebts({organizationId:d.currentUser.organization.id,url:d.url}),d.page,d.pageSize)};return {found:true,data:d.paged(d.fallbackList(),d.page,d.pageSize)}},
  getCustomerDebt:async()=>{const id=d.getCustomerId(d.path);if(d.repository.getCustomerDebt)return {found:true,data:await d.repository.getCustomerDebt({organizationId:d.currentUser.organization.id,customerId:id})};return {found:true,data:d.fallbackDetail(id)}},
 getCustomerOpenDebts:async()=>{const id=d.getCustomerId(d.path),amountParam=Number(d.url.searchParams.get('amount')??''),limitParam=Number(d.url.searchParams.get('limit')??''),amount=Number.isFinite(amountParam)&&amountParam>0?amountParam:undefined,limit=Number.isFinite(limitParam)&&limitParam>0?Math.max(1,Math.min(Math.floor(limitParam),100)):50;if(d.repository.getCustomerOpenDebts)return {found:true,data:await d.repository.getCustomerOpenDebts({organizationId:d.currentUser.organization.id,customerId:id,amount,limit})};return {found:true,data:d.sliceOpen(d.fallbackDetail(id).invoices,{amount,limit})}},
}}
