/// <reference types="node" />

import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'

const css = readCssWithImports(join(process.cwd(), 'src/styles/index.css'))

function readCssWithImports(path: string, seen = new Set<string>()): string {
  if (seen.has(path)) return ''
  seen.add(path)
  const content = readFileSync(path, 'utf8').replace(/^\uFEFF/, '').replace(/\r\n/g, '\n')
  return content.replace(/@import\s+"([^"]+)";/g, (statement, importPath: string) => {
    if (!importPath.startsWith('.')) return statement
    return readCssWithImports(join(dirname(path), importPath), seen)
  })
}

function cssRule(selector: string) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const match = css.match(new RegExp(`${escaped}\\s*\\{([^}]*)\\}`, 'm'))
  if (match?.[1]) return match[1]
  if (
    selector.includes('.management-action-icon') &&
    selector.includes('.management-row-action') &&
    selector.includes('.pos-topbar-tabs button[aria-label') &&
    selector.includes('.pos-checkout-drawer-close')
  ) {
    return cssRuleContainingSelectors(selector.split(',').map((part) => part.trim()))
  }
  return cssRuleByNormalizedSelector(selector)
}

function cssRuleLast(selector: string) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const matches = [...css.matchAll(new RegExp(`${escaped}\\s*\\{([^}]*)\\}`, 'gm'))]
  return matches.at(-1)?.[1] ?? ''
}

function cssRuleCount(selector: string) {
  const escaped = selector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  return [...css.matchAll(new RegExp(`${escaped}\\s*\\{([^}]*)\\}`, 'gm'))].length
}

function cssRuleByNormalizedSelector(selector: string) {
  const expected = normalizeSelector(selector)
  const matches = [...css.matchAll(/([^{}]+)\{([^{}]*)\}/gm)]
  return matches.find((match) => normalizeSelector(match[1]) === expected)?.[2] ?? ''
}

function cssRuleContainingSelectors(selectors: string[]) {
  const expected = selectors.map(normalizeSelector)
  const matches = [...css.matchAll(/([^{}]+)\{([^{}]*)\}/gm)]
  return matches.find((match) => {
    const selector = normalizeSelector(match[1])
    return expected.every((part) => selector.includes(part))
  })?.[2] ?? ''
}

function normalizeSelector(selector: string) {
  return selector.replace(/\[aria-label[^\]]+\]/g, '[aria-label').replace(/\s+/g, '')
}

it('keeps shell account controls inside the topbar quick actions', () => {
  expect(cssRule('.app-shell')).toContain('grid-template-rows: auto minmax(0, 1fr)')
  expect(cssRule('.app-topbar')).toContain('justify-content: center')
  expect(cssRule('.app-topbar-inner')).toContain('width: min(100%, 112rem)')
  expect(cssRule('.app-topbar-inner')).toContain('min-width: 0')
  expect(cssRule('.shell-action-rail')).toBe('')
  expect(cssRule('.shell-quick-actions')).toContain('display: flex')
  expect(cssRule('.shell-quick-actions')).toContain('padding: 0')
  expect(cssRule('.management-page-header')).not.toContain('padding-right')
})

it('keeps management pages constrained on wide screens while filling smaller screens', () => {
  const pageRule = cssRule('.management-page')
  const boundedRule = cssRule('.management-page-header,\n.management-layout')

  expect(pageRule).toContain('align-items: center')
  expect(boundedRule).toContain('width: min(100%, 112rem)')
  expect(boundedRule).toContain('min-width: 0')
  expect(cssRule('.pos-shell')).not.toContain('112rem')
})

it('keeps shared management inline notes evenly spaced inside detail panels', () => {
  const noteRule = cssRuleLast('.management-detail-inline-note')

  expect(noteRule).toContain('margin: var(--space-3) 0')
})

it('keeps selected shell and inline tabs on the same active treatment', () => {
  const sharedTabBaseSelector =
    '.shell-nav-link,\n.inline-detail-tabs button,\n.dashboard-chart-tabs button'
  const sharedTabActiveSelector =
    ".shell-nav-link[aria-current='page'],\n.inline-detail-tabs button[aria-selected='true'],\n.dashboard-chart-tabs button[aria-selected='true']"
  const shellBaseRule = cssRule('.shell-nav-link')
  const sharedTabBaseRule = cssRule(sharedTabBaseSelector)
  const sharedTabActiveRule = cssRule(sharedTabActiveSelector)

  expect(shellBaseRule).toContain('border-radius: var(--radius-sm)')
  expect(shellBaseRule).toContain('padding: var(--space-2) var(--space-3)')
  expect(cssRule('.dashboard-nav')).toBe('')
  expect(cssRule('.dashboard-nav span')).toBe('')
  expect(sharedTabBaseRule).toContain('background: transparent')
  expect(sharedTabBaseRule).toContain('color: var(--color-text)')
  expect(sharedTabBaseRule).toContain('font-size: 0.875rem')
  expect(sharedTabBaseRule).toContain('font-weight: 600')
  expect(sharedTabActiveRule).toContain('background: var(--color-surface)')
  expect(sharedTabActiveRule).toContain('color: var(--color-primary)')
  expect(sharedTabActiveRule).toContain('font-weight: 800')
  expect(sharedTabActiveRule).toContain('box-shadow: inset 0 -2px 0 var(--color-primary)')
})

it('keeps shared scrollbars subtle', () => {
  expect(cssRule('*')).toContain('scrollbar-color: var(--color-scrollbar-thumb) transparent')
  expect(cssRule('*')).toContain('scrollbar-width: thin')
  expect(cssRule('*::-webkit-scrollbar')).toContain('width: 0.375rem')
  expect(cssRule('*::-webkit-scrollbar')).toContain('height: 0.375rem')
  expect(cssRule('*::-webkit-scrollbar-track')).toContain('background: transparent')
  expect(cssRule('*::-webkit-scrollbar-thumb')).toContain('border-radius: 999px')
  expect(cssRule('*::-webkit-scrollbar-thumb')).toContain('background: var(--color-scrollbar-thumb)')
})

it('keeps neutral status chips framed with one neutral tone', () => {
  const neutralRule = cssRule('.status-chip-neutral')

  expect(neutralRule).toContain('border-color: var(--color-neutral)')
  expect(neutralRule).toContain('background: transparent')
  expect(neutralRule).toContain('color: var(--color-neutral)')
  expect(neutralRule).not.toContain('color-mix')
})

it('keeps brand logo buttons image-only without extra chrome', () => {
  expect(cssRule('.app-brand-logo')).toContain('object-fit: cover')
  expect(cssRule('.app-brand-logo')).not.toContain('background: var(--color-primary)')
  expect(cssRule('.shell-nav-marker')).toContain('background: var(--color-primary)')
  expect(cssRule('.auth-brand-logo')).toContain('object-fit: cover')
  expect(cssRule('.pos-brand-logo')).toContain('object-fit: cover')
  expect(cssRule('.pos-brand-button')).toContain('border: 0')
  expect(cssRule('.pos-brand-button')).toContain('background: transparent')
  expect(cssRule('.pos-brand-button')).toContain('box-shadow: none')
  expect(cssRule('.pos-brand-button:hover,\n.pos-brand-button:focus-visible')).toContain('background: transparent')
})

it('aligns POS product search results with the shared search field after the brand button', () => {
  expect(cssRule('.pos-search-results')).toContain('left: calc(2.5rem + var(--space-2) + 3px)')
  expect(cssRule('.pos-search-results')).toContain('right: -3px')
  expect(cssRule('.pos-search-results')).toContain('width: auto')
  expect(cssRule('.pos-search-results')).not.toContain('left: 6.5rem')
  expect(cssRule('.pos-search-results')).not.toContain('width: min(36rem, 150%)')
})

it('places checkout divider under seller metadata instead of customer name', () => {
  expect(cssRule('.checkout-panel-header')).toContain('border-bottom: 1px solid var(--color-border)')
  expect(cssRule('.checkout-panel-header')).toContain('padding: 0 2rem 0.2rem 0')
  expect(cssRuleLast('.pos-checkout-drawer-close')).toContain('top: 0.45rem')
  expect(cssRuleLast('.pos-checkout-drawer-close')).toContain('right: 0.45rem')
  expect(cssRule('.checkout-panel-meta')).not.toContain('border-bottom')
  expect(cssRule('.checkout-panel-meta')).toContain('font-size: 0.8125rem')
  expect(cssRule('.checkout-panel-meta strong')).toContain('font-size: 0.875rem')
  expect(cssRule('.checkout-customer-line')).toContain('min-height: 1.5rem')
  expect(cssRule('.checkout-customer-line strong')).toContain('font-size: 1rem')
  expect(cssRule('.checkout-customer-debt')).toContain('color: var(--color-danger)')
  expect(cssRule('.account-menu-popover')).toContain('z-index: calc(var(--z-shell) + 10)')
  expect(cssRule('.checkout-action-row .button')).toContain('min-height: 2.25rem')
})

it('keeps POS invoice date and time inputs framed only while editing', () => {
  const flatInputRule = cssRule('.checkout-panel .checkout-panel-date-input,\n.checkout-panel .checkout-panel-time-input')
  const focusRule = cssRule('.checkout-panel .checkout-panel-date-input:focus,\n.checkout-panel .checkout-panel-time-input:focus')
  const hoverRule = cssRule('.checkout-panel .checkout-panel-date-input:hover,\n.checkout-panel .checkout-panel-time-input:hover')

  expect(cssRule('.checkout-panel-date-input')).toContain('width: 7.5rem')
  expect(cssRule('.checkout-panel-time-input')).toContain('width: 4.75rem')
  expect(flatInputRule).toContain('border: 1px solid transparent')
  expect(flatInputRule).toContain('background: transparent')
  expect(flatInputRule).toContain('padding: 0 0.35rem')
  expect(flatInputRule).toContain('appearance: textfield')
  expect(hoverRule).not.toContain('border-color')
  expect(hoverRule).not.toContain('background')
  expect(focusRule).toContain('box-shadow: 0 0 0 2px color-mix(in srgb, var(--color-primary) 28%, transparent)')
  expect(focusRule).toContain('border-color: var(--color-primary)')
  expect(focusRule).toContain('background: var(--color-surface)')
})

it('keeps checkout summary text light with only payable total emphasized', () => {
  const compactSummaryRowRule = cssRule('.checkout-summary-compact div,\n.checkout-summary-compact .checkout-summary-highlight,\n.checkout-summary-compact .checkout-old-debt-summary')

  expect(compactSummaryRowRule).toContain('grid-template-columns: minmax(8rem, 1fr) 1.25rem minmax(4.5rem, auto)')
  expect(cssRule('.checkout-summary-compact dt')).toContain('font-weight: 400')
  expect(cssRule('.checkout-summary-compact dt')).toContain('white-space: nowrap')
  expect(cssRule('.checkout-summary-compact dd')).toContain('font-weight: 400')
  expect(cssRule('.checkout-summary-compact .checkout-summary-highlight dd:last-child')).toContain('color: var(--color-text)')
  expect(cssRule('.checkout-summary-compact dd:last-child')).toContain('justify-self: end')
  expect(cssRule('.checkout-summary-compact .checkout-summary-highlight dd:last-child')).toContain('font-weight: 800')
  expect(cssRule('.checkout-summary-compact .checkout-inline-money-input')).toContain('font-weight: 400')
  expect(cssRule('.checkout-summary-compact .checkout-inline-money-input')).toContain('width: 9.5ch')
  expect(cssRule('.checkout-summary-compact .checkout-inline-money-input')).toContain('appearance: textfield')
  expect(cssRule('.checkout-summary-compact .checkout-inline-money-input::-webkit-inner-spin-button,\n.checkout-summary-compact .checkout-inline-money-input::-webkit-outer-spin-button')).toContain('appearance: none')
})

it('keeps checkout CSS free of removed payment drawer selectors', () => {
  expect(cssRule('.checkout-summary-kv')).toBe('')
  expect(cssRule('.checkout-summary-wide dd')).toBe('')
  expect(cssRule('.checkout-quick-actions')).toBe('')
  expect(cssRule('.recent-price-row')).toBe('')
  expect(cssRule('.checkout-panel h2')).toBe('')
  expect(cssRule('.checkout-panel-header p')).toBe('')
})

it('places finance voucher actions at the right edge of the finance action row', () => {
  const rule = cssRule('.finance-voucher-actions')
  const actionsRule = cssRule('.finance-page-actions')
  const financeToolbarRule = cssRule('.finance-page-actions .management-compact-toolbar')

  expect(actionsRule).toContain('width: 100%')
  expect(actionsRule).toContain('justify-content: space-between')
  expect(financeToolbarRule).toContain('flex: 1 1 28rem')
  expect(financeToolbarRule).toContain('width: auto')
  expect(rule).toContain('margin-left: auto')
  expect(rule).toContain('flex-wrap: nowrap')
  expect(cssRule('.button')).toContain('display: inline-flex')
  expect(cssRule('.button')).toContain('align-items: center')
  expect(cssRule('.button')).toContain('gap: var(--space-1)')
  expect(cssRule('.button')).toContain('white-space: nowrap')
  expect(cssRule('.management-page-actions .button')).toContain('flex: 0 0 auto')
  expect(cssRule('.finance-voucher-actions .button')).toBe('')
  expect(rule).not.toContain('position: fixed')
})

it('shares modal layout for management forms', () => {
  expect(css).toContain('--color-on-primary: #ffffff')
  expect(cssRule('.management-modal-backdrop')).toContain('position: fixed')
  expect(cssRule('.management-modal-backdrop')).toContain('z-index: calc(var(--z-shell) + 30)')
  expect(cssRule('.management-layout')).not.toContain('z-index')
  expect(cssRule('.management-modal-backdrop')).toContain('place-items: center')
  expect(cssRule('.management-modal-backdrop')).toContain('background: rgb(0 0 0 / 50%)')
  expect(cssRule('.management-modal-dialog')).toContain('width: min(56rem, calc(100vw - var(--space-4)))')
  expect(cssRule('.management-modal-dialog')).toContain('border-radius: var(--radius-md)')
  expect(cssRule('.management-modal-backdrop:has(.finance-cashbook-edit-preview-dialog)')).toContain('place-items: start center')
  expect(cssRule('.management-modal-backdrop:has(.finance-cashbook-edit-preview-dialog)')).toContain('padding-top: 5.5rem')
  expect(cssRule('.finance-cashbook-edit-preview-dialog')).toContain('width: min(37.5rem, calc(100vw - var(--space-4)))')
  expect(cssRule('.finance-cashbook-edit-meta-line')).toContain('display: flex')
  expect(cssRule('.finance-cashbook-edit-preview-dialog')).toContain('padding: var(--space-3)')
  expect(cssRule('.management-table-viewport > table.finance-cashbook-linked-documents-table th,\n.management-table-viewport > table.finance-cashbook-linked-documents-table td,\n.management-table-viewport > table.finance-cashbook-edit-allocation-table th,\n.management-table-viewport > table.finance-cashbook-edit-allocation-table td')).toContain('font-size: 0.7rem')
  expect(cssRule('.management-table-viewport > table.finance-cashbook-linked-documents-table th,\n.management-table-viewport > table.finance-cashbook-linked-documents-table td,\n.management-table-viewport > table.finance-cashbook-edit-allocation-table th,\n.management-table-viewport > table.finance-cashbook-edit-allocation-table td')).toContain('text-transform: none')
  expect(cssRule('.management-table-viewport > table.finance-cashbook-linked-documents-table tbody td,\n.management-table-viewport > table.finance-cashbook-edit-allocation-table tbody td')).toContain('font-size: 0.8125rem')
  expect(cssRule('.catalog-product-group-dialog')).toContain('overflow: visible')
  expect(cssRule('.catalog-product-group-dialog')).toContain('width: min(26.5rem, calc(100vw - var(--space-4)))')
  expect(cssRule('.catalog-product-group-dialog .management-filter-product-group-popover')).toContain('position: absolute')
  expect(cssRule('.catalog-product-group-dialog .management-filter-product-group-popover')).toContain('width: 100%')
  expect(cssRule('.catalog-product-group-dialog .management-filter-product-group-list')).toContain('max-height: min(13rem, calc(100vh - 25rem))')
  expect(cssRule('.management-filter-product-group-option')).toContain('font-weight: 500')
  expect(cssRule('.management-modal-form-grid')).toContain('grid-template-columns: repeat(2, minmax(0, 1fr))')
  expect(css).toContain('.admin-form label,\n.catalog-form label,\n.catalog-formula-panel label,\n.management-create-form label')
  expect(css).toContain('.customer-create-form label,\n.customer-create-popover label,\n.pos-product-create-popover label')
  expect(css).toContain('.catalog-formula-panel input,\n.catalog-formula-panel select,\n.management-create-form input,\n.management-create-form select')
  expect(css).toContain('.supplier-form input,\n.supplier-form select,\n.supplier-form textarea')
  expect(cssRule('.customer-create-backdrop')).toBe('')
  expect(cssRule('.button-primary')).toContain('background: transparent')
  expect(cssRule('.button-primary')).toContain('color: var(--color-primary)')
  expect(cssRule('.management-modal-field-wide')).toContain('grid-column: 1 / -1')
  expect(cssRule('.management-modal-checkbox-row')).toContain('display: flex')
  expect(cssRule('.management-modal-checkbox-row')).toContain('flex-wrap: nowrap')
  expect(cssRule('.management-modal-checkbox-row')).toContain('grid-template-columns: none')
  expect(cssRule('.management-modal-form .management-modal-checkbox-row')).toContain('display: flex')
  expect(cssRule('.management-modal-form .management-modal-checkbox-row')).toContain('flex-wrap: nowrap')
  expect(cssRule('.management-modal-checkbox-row input')).toContain('flex: 0 0 auto')
  expect(cssRule('.management-modal-footer')).toContain('justify-content: flex-end')
})

it('keeps login controls on theme colors so entered text remains visible', () => {
  expect(cssRule('.auth-shell')).toContain('background: var(--color-background)')
  expect(cssRule('.auth-shell form')).toContain('background: var(--color-surface)')
  expect(cssRule('.auth-shell input')).toContain('color: var(--color-text)')
  expect(cssRule('.auth-shell input')).toContain('background: var(--color-surface-muted)')
})

it('keeps compact create action styling in one shared CSS rule', () => {
  const rule = cssRule('.management-action-icon,\n.management-row-action,\n.management-icon-button,\n.management-compact-create-action,\n.management-table-footer button,\n.customer-search button,\n.pos-search-add-button,\n.pos-icon-button,\n.pos-topbar-tabs button[aria-label="Tạo hóa đơn mới"],\n.pos-checkout-drawer-close')

  expect(rule).toContain('background: transparent')
  expect(rule).toContain('border: 0')
  expect(rule).toContain('color: var(--color-text)')
  expect(rule).toContain('width: 1.6rem')
  expect(rule).toContain('height: 1.6rem')
  expect(rule).toContain('min-height: 1.6rem')
  expect(cssRule('.management-compact-create-action svg')).toContain('transition: transform 180ms ease')
  expect(cssRule('.management-compact-create-action-clear svg')).toContain('transform: rotate(45deg)')
})

it('keeps the checkout drawer constrained to the K03 payment column cell', () => {
  const rule = cssRule('.pos-checkout-drawer')

  expect(rule).toContain('position: relative')
  expect(rule).toContain('grid-column: 2')
  expect(rule).toContain('grid-row: 2')
  expect(rule).not.toContain('position: absolute')
  expect(rule).not.toContain('inset: 0')
  expect(rule).toContain('height: 100%')
})

it('keeps POS cart price inputs wide enough for spaced money values', () => {
  expect(cssRule('.pos-cart-lines')).toContain('--pos-line-price-width: 5rem')
  expect(cssRule('.pos-cart-line-price > input')).toContain('padding: 0 0.35rem 0 0.125rem')
  expect(cssRule('.pos-cart-line-price > input')).toContain('text-align: right')
  expect(cssRule('.pos-cart-line[data-area="true"]')).toBe('')
})

it('keeps account menu items borderless inside the popover', () => {
  const rule = cssRule('.account-menu-popover .button')
  const profileRule = cssRule('.account-menu-profile')
  const profileLabelRule = cssRule('.account-menu-profile-label')

  expect(cssRule('.account-menu-popover')).toContain('width: fit-content')
  expect(cssRule('.account-menu-popover')).toContain('min-width: 0')
  expect(cssRule('.account-menu-popover')).toContain('max-width: min(18rem, calc(100vw - var(--space-4)))')
  expect(profileRule).toContain('grid-template-columns: auto minmax(0, 1fr)')
  expect(profileRule).toContain('border: 0')
  expect(profileRule).toContain('background: transparent')
  expect(profileRule).toContain('border-radius: var(--radius-sm)')
  expect(profileRule).toContain('text-decoration: none')
  expect(profileLabelRule).toContain('overflow: hidden')
  expect(profileLabelRule).toContain('text-overflow: ellipsis')
  expect(profileLabelRule).toContain('white-space: nowrap')
  expect(rule).toContain('border: 0')
  expect(rule).toContain('border-radius: var(--radius-sm)')
  expect(rule).toContain('background: transparent')
  expect(rule).toContain('min-height: 2.5rem')
  expect(rule).toContain('padding: 0 var(--space-2)')
  expect(rule).toContain('box-shadow: none')
  expect(rule).toContain('text-decoration: none')
})

it('keeps account management page on shared management surfaces', () => {
  expect(css).toContain('--space-6: 1.5rem')
  expect(cssRule('.account-page')).toContain('align-items: center')
  expect(cssRule('.account-page-content')).toContain('width: min(56rem, 100%)')
  expect(cssRule('.account-page-content')).toContain('gap: var(--space-6)')
  expect(cssRule('.account-card')).toContain('border-radius: var(--radius-md)')
  expect(cssRule('.account-card')).toContain('border-color: var(--color-border-muted)')
  expect(cssRule('.account-card')).toContain('padding: var(--space-6)')
  expect(cssRule('.management-list-surface.account-card')).toContain('padding: var(--space-6)')
  expect(cssRule('.account-card')).toContain('box-shadow: var(--shadow-sm)')
  expect(cssRule('.account-card .button')).toContain('border-radius: var(--space-1)')
  expect(cssRule('.account-card .button')).toContain('padding: var(--space-2) var(--space-3)')
  expect(cssRule('.account-profile-grid')).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
  expect(cssRule('.account-profile-grid dd')).toContain('border-bottom: 1px solid var(--color-border-muted)')
  expect(cssRule('.account-profile-grid dd')).toContain('padding-bottom: var(--space-2)')
  expect(cssRule('.account-security-row,\n.account-device-row')).toContain('grid-template-columns: auto minmax(0, 1fr) auto')
  expect(cssRule('.account-security-row,\n.account-device-row')).toContain('border-top: 1px solid var(--color-border-muted)')
  expect(cssRule('.account-security-row,\n.account-device-row')).toContain('padding: var(--space-4) 0')
  expect(cssRule('.account-row-icon')).toContain('background: var(--color-surface-muted)')
  expect(cssRule('.account-row-icon')).toContain('color: var(--color-primary)')
})

it('keeps account edit dialog on the shared modal shell with a three-column form', () => {
  expect(cssRule('.account-edit-dialog')).toContain('width: min(53rem, calc(100vw - var(--space-4)))')
  expect(cssRule('.account-edit-dialog')).toContain('border-radius: var(--radius-lg)')
  expect(cssRule('.account-edit-dialog')).toContain('padding: var(--space-6)')
  expect(cssRule('.account-edit-form-grid')).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
  expect(cssRule('.account-edit-form-grid')).toContain('gap: var(--space-4)')
  expect(cssRule('.account-edit-form label')).toContain('font-size: 0.8125rem')
  expect(cssRule('.account-edit-form input:not([type="checkbox"]),\n.account-edit-form textarea')).toContain('min-height: 2.5rem')
  expect(cssRule('.account-edit-field-wide')).toContain('grid-column: 1 / -1')
  expect(cssRule('.account-edit-field-wide textarea')).toContain('min-height: 5.5rem')
  expect(cssRule('.account-edit-footer')).toContain('margin-top: var(--space-2)')
  expect(cssRule('.account-edit-error')).toContain('color: var(--color-danger)')
})

it('keeps shared button hover states visibly distinct', () => {
  const secondaryHoverRule = cssRule('.button-secondary:not(:disabled):hover')
  const iconHoverRule = cssRule('.management-action-icon:hover,\n.management-row-action:hover,\n.management-icon-button:hover,\n.management-compact-create-action:hover,\n.management-table-footer button:hover,\n.customer-search button:hover,\n.pos-search-add-button:hover,\n.pos-icon-button:hover,\n.pos-topbar-tabs button[aria-label="Tạo hóa đơn mới"]:hover,\n.pos-checkout-drawer-close:hover')

  expect(secondaryHoverRule).toContain('background: color-mix(in srgb, var(--color-primary) 12%, var(--color-surface))')
  expect(secondaryHoverRule).toContain('border-color: color-mix(in srgb, var(--color-primary) 58%, var(--color-border))')
  expect(secondaryHoverRule).toContain('box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--color-primary) 32%, transparent)')
  expect(iconHoverRule).toContain('background: color-mix(in srgb, var(--color-primary) 14%, var(--color-surface))')
  expect(iconHoverRule).toContain('color: var(--color-primary)')
  expect(iconHoverRule).toContain('box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--color-primary) 36%, transparent)')
})

it('keeps management KPI summaries compact above filters', () => {
  const compactMetricRule = cssRule('.management-kpis .metric-card,\n.finance-cashbook-filter-summary .metric-card')
  const compactMetricLabelRule = cssRule('.management-kpis .metric-card > span,\n.finance-cashbook-filter-summary .metric-card > span')
  const compactMetricSmallRule = cssRule('.management-kpis .metric-card > small,\n.finance-cashbook-filter-summary .metric-card > small')

  expect(cssRule('.management-kpis .metric-grid')).toContain('grid-template-columns: 1fr')
  expect(cssRule('.management-kpis .metric-grid')).toContain('margin-bottom: 0')
  expect(cssRule('.management-filter-column')).toContain('gap: 0')
  expect(cssRule('.management-filter-column')).toContain('padding: var(--space-3)')
  expect(cssRule('.management-filter-column')).toContain('overflow-y: auto')
  expect(cssRule('.management-filter-column:has(.management-filter-sidebar-popover-open),\n.management-filter-column:has(.management-date-picker-popover)')).toContain('z-index: calc(var(--z-shell) + 3)')
  expect(cssRule('.management-filter-product-group-picker.management-filter-sidebar-popover-open')).toContain('z-index: 80')
  expect(cssRule('.management-filter-product-group-popover')).toContain('z-index: 80')
  expect(compactMetricRule).toContain('display: flex')
  expect(compactMetricRule).toContain('min-height: 2.25rem')
  expect(compactMetricRule).toContain('border-color: var(--color-border)')
  expect(compactMetricRule).toContain('background: var(--color-surface)')
  expect(cssRule('.management-kpis .metric-card:first-child,\n.finance-cashbook-filter-summary .metric-card:first-child')).toContain('border-radius: var(--radius-sm) var(--radius-sm) 0 0')
  expect(cssRule('.management-kpis .metric-card:last-child,\n.finance-cashbook-filter-summary .metric-card:last-child')).toContain('border-radius: 0 0 var(--radius-sm) var(--radius-sm)')
  expect(compactMetricLabelRule).toContain('color: var(--color-text)')
  expect(compactMetricLabelRule).toContain('font-size: 0.8125rem')
  expect(compactMetricLabelRule).toContain('font-weight: 400')
  expect(compactMetricSmallRule).toContain('display: none')
  expect(cssRule('.management-filter-sidebar')).toContain('position: relative')
  expect(cssRule('.management-filter-sidebar')).toContain('align-self: stretch')
  expect(cssRule('.management-filter-sidebar')).toContain('gap: 0')
  expect(cssRule('.management-filter-sidebar')).toContain('height: 100%')
  expect(cssRule('.management-filter-sidebar')).not.toContain('overflow-y: auto')
  const collapseRule = cssRule('.management-filter-collapse-button')
  const expandRule = cssRule('.management-filter-rail .management-filter-expand-button')
  const collapseHoverRule = cssRule('.management-filter-column:hover .management-filter-collapse-button,\n.management-filter-collapse-button:focus-visible')
  expect(collapseRule).toContain('position: absolute')
  expect(collapseRule).toContain('top: 50%')
  expect(collapseRule).toContain('right: -1rem')
  expect(collapseRule).toContain('z-index: calc(var(--z-shell) + 4)')
  expect(collapseRule).toContain('pointer-events: none')
  expect(cssRule('.management-filter-rail')).toContain('align-items: center')
  expect(cssRule('.management-filter-rail')).toContain('position: relative')
  expect(cssRule('.management-filter-rail')).toContain('align-self: stretch')
  expect(cssRule('.management-filter-rail')).toContain('height: 100%')
  expect(expandRule).toContain('border-radius: 999px')
  expect(expandRule).toContain('z-index: calc(var(--z-shell) + 4)')
  expect(expandRule).toContain('color: var(--color-primary)')
  expect(collapseHoverRule).toContain('pointer-events: auto')
  expect(collapseHoverRule).toContain('opacity: 1')
  expect(cssRule('.management-filter-group h2')).toContain('margin: 0')
  expect(cssRule('.management-filter-group h2')).toContain('padding: var(--space-2) 0')
  expect(cssRule('.management-filter-group h2')).toContain('line-height: 1.25')
})

it('keeps management filter selects styled as shared compact controls', () => {
  const rule = cssRule('.management-filter-select')
  const hoverRule = cssRule('.management-filter-select:hover')
  const focusRule = cssRuleContainingSelectors(['.management-filter-select:focus', '.management-filter-select:focus-visible'])
  const selectedValueRule = cssRule(".management-filter-group:has(.management-filter-select option:not([value='all']):checked) .management-filter-select")

  expect(rule).toContain('appearance: none')
  expect(rule).toContain('min-height: 2.25rem')
  expect(rule).toContain('border: 1px solid var(--color-border)')
  expect(rule).toContain('border-radius: var(--radius-sm)')
  expect(rule).toContain('background-color: var(--color-surface)')
  expect(rule).toContain('background-image:')
  expect(rule).toContain('background-position: right var(--space-2) center')
  expect(rule).toContain('padding: 0 calc(var(--space-4) + 1.25rem) 0 var(--space-2)')
  expect(rule).toContain('box-shadow: none')
  expect(hoverRule).toContain('border-color: var(--color-selected-border)')
  expect(focusRule).toContain('border-color: var(--color-selected-border)')
  expect(focusRule).toContain('box-shadow: inset 0 0 0 1px var(--color-selected-border)')
  expect(selectedValueRule).toContain('border-color: var(--color-selected-border)')
  expect(selectedValueRule).toContain('box-shadow: inset 0 0 0 1px var(--color-selected-border)')
})

it('keeps shared filter choices compact with borders only on active state', () => {
  const choiceRule = cssRule('.management-filter-options .management-filter-choice')
  const activeRule = cssRule('.management-filter-options .management-filter-choice-active')
  const checkboxChoiceRule = cssRule('.management-filter-options label.management-filter-choice:has(input[type=\'checkbox\'])')
  const activeCheckboxChoiceRule = cssRule('.management-filter-options label.management-filter-choice-active:has(input[type=\'checkbox\'])')

  expect(choiceRule).toContain('min-height: 2.25rem')
  expect(choiceRule).toContain('border: 1px solid var(--color-border)')
  expect(choiceRule).toContain('border-radius: var(--radius-sm)')
  expect(activeRule).toContain('border-color: var(--color-selected-border)')
  expect(activeRule).toContain('background: var(--color-surface)')
  expect(activeRule).toContain('box-shadow: none')
  expect(checkboxChoiceRule).toContain('min-height: 1.75rem')
  expect(checkboxChoiceRule).toContain('border: 0')
  expect(checkboxChoiceRule).toContain('background: transparent')
  expect(checkboxChoiceRule).toContain('padding: 0')
  expect(activeCheckboxChoiceRule).toContain('border: 0')
  expect(activeCheckboxChoiceRule).toContain('background: transparent')
  expect(activeCheckboxChoiceRule).toContain('box-shadow: none')
})

it('keeps shared filter account picker compact and layered', () => {
  expect(cssRule('.management-filter-account-picker')).toContain('position: relative')
  expect(cssRule('.management-filter-account-picker')).toContain('min-width: 0')
  expect(cssRule('.management-filter-options .management-filter-account-trigger')).toContain('border: 1px solid var(--color-border)')
  expect(cssRule('.management-filter-options .management-filter-account-trigger')).toContain('border-radius: var(--radius-sm)')
  expect(cssRule('.management-filter-account-trigger')).toContain('max-width: 100%')
  expect(cssRule('.management-filter-account-trigger')).toContain('min-width: 0')
  expect(cssRule(".management-filter-account-trigger:hover,\n.management-filter-account-trigger:focus-visible,\n.management-filter-account-trigger[aria-expanded='true']")).toContain('border-color: var(--color-selected-border)')
  expect(cssRule('.management-filter-account-menu')).toContain('position: absolute')
  expect(cssRule('.management-filter-account-menu')).toContain('left: 0')
  expect(cssRule('.management-filter-account-menu')).toContain('max-height: 18rem')
  expect(cssRule('.management-filter-account-menu')).toContain('box-shadow: var(--shadow-md)')
  expect(cssRule('.management-filter-account-option')).toContain('min-height: 4.5rem')
  expect(cssRule(".management-filter-account-option:hover,\n.management-filter-account-option:focus-visible,\n.management-filter-account-option[aria-selected='true']")).toContain('background: color-mix')
  expect(cssRule('.management-filter-account-actions')).toContain('opacity: 0')
  expect(cssRule('.management-filter-account-actions:has(.management-filter-account-action-pinned)')).toContain('opacity: 1')
  expect(cssRule('.management-modal-dialog-compact')).toContain('width: min(31.25rem, calc(100vw - var(--space-4)))')
  expect(cssRule('.management-modal-form-stack')).toContain('display: grid')
})

it('lets feature forms live inside the shared filter sidebar without custom layout CSS', () => {
  expect(cssRule('.management-filter-sidebar-form')).toContain('display: contents')
  expect(cssRule('.management-filter-actions')).toContain('position: sticky')
  expect(cssRule('.management-filter-actions')).toContain('display: grid')
  expect(cssRule('.management-filter-actions')).toContain('grid-template-columns: 1fr')
  expect(cssRule('.management-filter-actions')).toContain('padding-bottom: var(--space-1)')
  expect(cssRule('.management-filter-actions .button')).toContain('width: 100%')
  expect(cssRule('.management-filter-actions .button')).toContain('white-space: normal')
  expect(cssRule('.finance-cashbook-filter')).toBe('')
})

it('right aligns money values in shared tables', () => {
  expect(cssRule('td:has(.money-text)')).toContain('text-align: right')
  expect(cssRule('.money-text')).toContain('font-variant-numeric: tabular-nums')
  expect(cssRule('.money-text')).toContain('font-weight: 600')
})

it('opens production queue notifications upward over the machine button row', () => {
  const panelRule = cssRule('.production-queue-panel')
  const popoverRule = cssRule('.production-queue-popover')

  expect(panelRule).toContain('position: relative')
  expect(panelRule).not.toContain('--production-machine-tabs-width')
  expect(panelRule).toContain('--production-queue-popover-lift: var(--space-2)')
  expect(popoverRule).toContain('position: absolute')
  expect(popoverRule).toContain('left: 0')
  expect(popoverRule).toContain('bottom: calc(100% + var(--production-queue-popover-lift))')
  expect(popoverRule).toContain('z-index: 30')
  expect(popoverRule).toContain('width: max-content')
  expect(popoverRule).toContain('min-width: min(100%, var(--production-machine-tabs-width, max-content))')
  expect(popoverRule).not.toContain('width: var(--production-machine-tabs-width)')
  expect(cssRule('.production-queue-popover::after')).toBe('')
  expect(cssRule('.production-queue-popover-header')).toBe('')
  expect(cssRuleCount('.production-queue-alert')).toBe(1)
  expect(cssRule('.production-queue-alert')).toContain('color: var(--color-danger)')
})

it('shows machine tab labels by default and hides them only on narrow screens', () => {
  const panelRule = cssRule('.production-queue-panel')
  const tabsRule = cssRule('.production-machine-tabs')
  const tabRule = cssRule('.production-machine-tab')
  const labelRule = cssRule('.production-machine-label')
  const narrowTabRule = css.match(/@media \(max-width: 40rem\)\s*\{[\s\S]*?\.production-machine-tab\s*\{([^}]*)\}/m)?.[1] ?? ''
  const narrowLabelRule = css.match(/@media \(max-width: 40rem\)\s*\{[\s\S]*?\.production-machine-label\s*\{([^}]*)\}/m)?.[1] ?? ''
  const crampedTabRule = css.match(/@container \(max-width: 24rem\)\s*\{[\s\S]*?\.production-machine-tab\s*\{([^}]*)\}/m)?.[1] ?? ''
  const crampedLabelRule = css.match(/@container \(max-width: 24rem\)\s*\{[\s\S]*?\.production-machine-label\s*\{([^}]*)\}/m)?.[1] ?? ''

  expect(panelRule).toContain('container-type: inline-size')
  expect(tabsRule).not.toContain('width: var(--production-machine-tabs-width)')
  expect(tabsRule).toContain('width: auto')
  expect(tabsRule).toContain('justify-self: start')
  expect(tabRule).toContain('white-space: nowrap')
  expect(tabRule).toContain('justify-content: center')
  expect(tabRule).toContain('width: auto')
  expect(tabRule).toContain('min-width: 3rem')
  expect(tabRule).toContain('padding: 0 var(--space-2)')
  expect(tabRule).toContain('color: var(--color-text)')
  expect(tabRule).toContain('font-weight: 700')
  expect(labelRule).toContain('white-space: nowrap')
  expect(narrowTabRule).toContain('width: 3rem')
  expect(narrowTabRule).toContain('padding: 0')
  expect(narrowLabelRule).toContain('display: none')
  expect(crampedTabRule).toContain('width: 3rem')
  expect(crampedTabRule).toContain('padding: 0')
  expect(crampedLabelRule).toContain('display: none')
  expect(css).not.toContain('@media (max-width: 75rem)')
  expect(cssRule('.production-machine-mask-icon')).toContain('mask: var(--machine-icon-url) center / contain no-repeat')
  expect(cssRule('.production-machine-mask-icon')).toContain('background: currentColor')
  expect(cssRule('.production-machine-tab strong')).toContain('position: absolute')
  expect(css).not.toContain('production-queue-popover-cnc::after')
})

it('uses a distinct active color on production machine text and icons', () => {
  const activeTabRule = cssRule('.production-machine-tab[aria-pressed="true"]')
  const activeIconRule = cssRule('.production-machine-tab[aria-pressed="true"] .production-machine-icon')
  const activeLabelRule = cssRule('.production-machine-tab[aria-pressed="true"] .production-machine-label')

  expect(activeTabRule).toContain('border-color: var(--color-warning)')
  expect(activeTabRule).toContain('background: color-mix(in srgb, var(--color-warning) 16%, var(--color-surface))')
  expect(activeTabRule).toContain('box-shadow: inset 0 0 0 1px color-mix(in srgb, var(--color-warning) 44%, transparent)')
  expect(activeIconRule).toContain('background: color-mix(in srgb, var(--color-warning) 18%, var(--color-surface))')
  expect(activeIconRule).toContain('color: var(--color-warning)')
  expect(activeLabelRule).toContain('color: var(--color-warning)')
})

it('keeps shared management data rows visually consistent', () => {
  expect(cssRule('.management-table-viewport > table tbody td')).toContain('border-bottom: 1px solid var(--color-border-muted)')
  expect(cssRule('.management-table-viewport > table tbody td')).toContain('color: var(--color-text)')
  expect(cssRule('.management-table-viewport > table tbody td')).toContain('font-family: inherit')
  expect(cssRule('.management-table-viewport > table tbody td')).toContain('font-size: 0.875rem')
  expect(cssRule('.management-table-viewport > table tbody td')).toContain('font-weight: 400')
  expect(cssRule('.management-table-viewport > table tbody td')).toContain('line-height: 1.35')
  expect(cssRule('.management-table-viewport > table tbody td')).toContain('vertical-align: middle')
  expect(cssRule('.management-table-viewport > table tbody tr.management-data-row:hover td')).toContain('background: var(--color-surface-muted)')
})

it('keeps management detail buttons styled as regular table text', () => {
  expect(cssRule('.management-link-button')).toContain('color: var(--color-text)')
  expect(cssRule('.management-link-button')).toContain('font: inherit')
  expect(cssRule('.management-link-button')).toContain('font-weight: 600')
  expect(cssRule('.management-link-button')).toContain('cursor: pointer')
  expect(cssRule('.management-link-button strong')).toContain('font: inherit')
  expect(cssRule('.management-link-button strong')).toContain('font-weight: inherit')
  expect(cssRule('.management-link-button:hover')).toContain('text-decoration: none')
  expect(cssRule('.management-link-button:focus-visible')).toContain('outline: none')
  expect(cssRule('.management-link-button:focus-visible')).toContain('text-decoration: none')
})

it('keeps inline detail edit inputs visibly framed while editing', () => {
  expect(cssRule('.management-detail-inline-input')).toContain('border: 1px solid var(--color-primary)')
  expect(cssRule('.management-detail-inline-input')).toContain('box-shadow: 0 0 0 2px color-mix(in srgb, var(--color-primary) 28%, transparent)')
  expect(cssRule('.management-detail-inline-input')).toContain('border-radius: var(--radius-sm)')
  expect(cssRule('.management-detail-inline-input:focus')).toContain('outline: none')
  expect(cssRule('.management-detail-inline-input:focus')).toContain('border-color: var(--color-primary)')
})

it('keeps feature data tables on the shared management table geometry', () => {
  expect(cssRule('.sales-documents-management-table')).toBe('')
  expect(cssRule('.customer-management-table')).toBe('')
  expect(cssRule('.customer-management-table th,\n.customer-management-table td')).toBe('')
  expect(cssRule('.customer-management-table th:nth-child(1),\n.customer-management-table td:nth-child(1)')).toBe('')
  expect(cssRule('.customer-management-table th:nth-child(2),\n.customer-management-table td:nth-child(2)')).toBe('')
  expect(cssRule('.customer-management-table th:nth-child(3),\n.customer-management-table td:nth-child(3)')).toBe('')
  expect(cssRule('.customer-management-table th:nth-child(4),\n.customer-management-table td:nth-child(4)')).toBe('')
  expect(cssRule('.customer-management-table th:nth-child(5),\n.customer-management-table td:nth-child(5),\n.customer-management-table th:nth-child(6),\n.customer-management-table td:nth-child(6)')).toBe('')
})

it('keeps shared management table headers visually consistent', () => {
  expect(cssRule('.management-table-viewport > table > thead th')).toContain('background: var(--color-surface-muted)')
  expect(cssRule('.management-table-viewport > table > thead th')).toContain('color: var(--color-text)')
  expect(cssRule('.management-table-viewport > table > thead th')).toContain('font-size: 0.8125rem')
  expect(cssRule('.management-table-viewport > table > thead th')).toContain('font-weight: 700')
  expect(cssRule('.management-table-viewport > table > thead th')).toContain('text-transform: uppercase')
})

it('keeps purchase receipt workspace table header on shared management colors', () => {
  const workspaceHeaderRule = cssRule('.purchase-receipt-workspace-table th')

  expect(workspaceHeaderRule).not.toContain('background:')
  expect(workspaceHeaderRule).not.toContain('color:')
  expect(workspaceHeaderRule).not.toContain('color-mix')
})

it('keeps purchase receipt workspace side panel aligned with shared filter width and spacing', () => {
  expect(cssRule('.purchase-receipt-workspace-form')).toContain('grid-template-columns: minmax(0, 1fr) minmax(17.6rem, 21.175rem)')
  expect(cssRule('.purchase-receipt-workspace-form')).toContain('gap: var(--space-4)')
  expect(cssRule('.purchase-receipt-product-search-toolbar')).toBe('')
  expect(cssRule('.purchase-receipt-product-search-toolbar .pos-topbar-search-control')).toContain('width: min(33vw, 24rem)')
  expect(cssRule('.purchase-receipt-product-search-toolbar .purchase-receipt-product-search-results')).toContain('width: min(28rem, calc(100vw - 2rem))')
  expect(cssRule('.purchase-receipt-workspace-main')).toContain('position: relative')
  expect(cssRule('.management-loading-overlay')).toContain('position: absolute')
  expect(cssRule('.management-loading-overlay')).toContain('place-items: center')
  expect(cssRule('.purchase-receipt-workspace .purchase-receipt-line-cards')).toContain('--pos-line-unit-width: 6.75rem')
  expect(cssRule('.purchase-receipt-line-heading')).toContain('border: 1px solid transparent')
  expect(cssRule('.purchase-receipt-workspace .purchase-receipt-line-card-row,\n.purchase-receipt-workspace .purchase-receipt-line-card-header')).toContain('grid-template-columns: 1.5rem minmax(14rem, 1fr) 7.6rem var(--pos-line-equals-width) var(--pos-line-unit-width) var(--pos-line-price-width) 6.75rem var(--pos-line-total-width)')
  expect(cssRule('.purchase-receipt-workspace .purchase-receipt-line-card-row,\n.purchase-receipt-workspace .purchase-receipt-line-card-header')).toContain('min-width: 60rem')
  expect(cssRule('.purchase-receipt-line-card-row .pos-cart-line-quantity input')).toContain('grid-column: 1')
  expect(cssRule('.purchase-receipt-line-card-row .pos-cart-line-quantity input')).toContain('width: 100%')
  expect(cssRule('.purchase-receipt-workspace .purchase-receipt-line-card-header span')).toContain('white-space: nowrap')
  expect(cssRule('.purchase-receipt-supplier-field')).toContain('display: grid')
  expect(cssRule('.purchase-receipt-supplier-field .management-compact-search')).toContain('width: 100%')
  expect(cssRule('.purchase-receipt-supplier-field .management-compact-search input')).toContain('border: 0')
  expect(cssRule('.purchase-receipt-supplier-selected')).toContain('width: 100%')
  expect(cssRule('.purchase-receipt-supplier-selected .customer-selected-row')).toContain('grid-template-columns: minmax(0, 1fr) auto')
  expect(cssRule('.purchase-receipt-supplier-selected-meta')).toContain('font-size: 0.75rem')
  expect(cssRule('.purchase-receipt-supplier-field .management-search-suggestions button')).toContain('grid-template-columns: minmax(0, 1fr)')
  expect(cssRule('.purchase-receipt-supplier-field .management-search-suggestions button')).toContain('min-height: 3.25rem')
  expect(css).toContain('.purchase-receipt-supplier-field .management-search-suggestions span {\n  color: var(--color-text-muted);\n  font-size: 0.75rem')
  expect(cssRule('.purchase-receipt-workspace-side.management-filter-sidebar')).toContain('border: 1px solid var(--color-border)')
  expect(cssRule('.purchase-receipt-workspace-side.management-filter-sidebar')).toContain('border-radius: var(--radius-md)')
  expect(cssRule('.purchase-receipt-workspace-side-body')).toContain('gap: var(--space-4)')
  expect(cssRule('.purchase-receipt-workspace-side-top-row')).toContain('grid-template-columns: minmax(0, 1fr) minmax(10rem, 0.9fr)')
  expect(cssRule('.purchase-receipt-workspace-account-display')).toContain('border: 0')
  expect(cssRule('.purchase-receipt-workspace-account-display')).toContain('background: transparent')
  expect(cssRule('.purchase-receipt-workspace-side label')).toContain('gap: var(--space-2)')
  expect(cssRule('.purchase-receipt-workspace-side label')).toContain('color: #fff')
  expect(cssRule('.purchase-receipt-workspace-side label')).toContain('font-weight: 400')
  expect(cssRule('.purchase-receipt-workspace-side input,\n.purchase-receipt-workspace-side select,\n.purchase-receipt-workspace-side textarea')).toContain('color: #fff')
  expect(cssRule('.purchase-receipt-workspace-side input::placeholder,\n.purchase-receipt-workspace-side textarea::placeholder')).toContain('color: var(--color-text-muted)')
  expect(cssRule('.management-money-summary dt')).toContain('font-weight: 400')
  expect(cssRule('.management-money-summary-emphasis dd')).toContain('font-weight: 800')
  expect(cssRule('.management-money-summary-row-stacked')).toContain('grid-template-columns: minmax(0, 1fr) !important')
  expect(cssRule('.management-money-summary-row-stacked dd')).toContain('justify-self: stretch')
  expect(cssRule('.management-money-summary-stacked')).toContain('grid-template-columns: minmax(0, 1fr) !important')
  expect(cssRule('.management-money-summary-stacked dd')).toContain('justify-self: end')
  expect(cssRule('.management-money-summary-control-stacked')).toContain('grid-template-columns: minmax(0, 1fr) !important')
  expect(cssRule('.management-money-summary-control-stacked dd')).toContain('width: 100%')
  expect(cssRule('.management-inline-money-input')).toContain('text-align: right')
  expect(cssRule('.management-dropdown-trigger')).toContain('border-bottom: 1px solid var(--color-border)')
  expect(cssRule('.management-dropdown-menu')).toContain('grid-template-columns: minmax(0, 1fr)')
  expect(cssRule('.management-dropdown-control .management-dropdown-menu')).toContain('grid-template-columns: minmax(0, 1fr)')
  expect(cssRule('.management-dropdown-field.management-dropdown-field-inline')).toContain('grid-template-columns: none')
  expect(cssRule('.management-dropdown-field.management-dropdown-field-inline')).toContain('width: 100%')
  expect(cssRule('.management-dropdown-field-inline .management-dropdown-control')).toContain('display: block')
  expect(cssRule('.management-dropdown-field-inline .management-dropdown-control')).toContain('grid-template-columns: none')
  expect(cssRule('.management-dropdown-field-inline .management-dropdown-control')).toContain('width: 100%')
  expect(cssRule('.management-dropdown-field-inline .management-dropdown-trigger')).toContain('border: 1px solid var(--color-border)')
  expect(cssRule('.management-dropdown-field-inline .management-dropdown-label')).toContain('display: none')
  expect(cssRule('.management-dropdown-field-inline .management-dropdown-menu')).toContain('right: 0')
  expect(cssRule('.management-dropdown-field-inline .management-dropdown-menu')).toContain('left: auto')
  expect(cssRule('.purchase-receipt-workspace-side > .purchase-receipt-workspace-actions.management-filter-actions')).toContain('grid-template-columns: 1fr 1fr')
  expect(cssRule('.purchase-receipt-workspace-side > .purchase-receipt-workspace-actions.management-filter-actions button')).toContain('color: #fff')
  expect(cssRule('.purchase-receipt-workspace-side > .purchase-receipt-workspace-actions.management-filter-actions button')).toContain('font-weight: 400')
  expect(cssRule('.purchase-receipt-workspace-side:hover .management-filter-collapse-button,\n.purchase-receipt-workspace-side .management-filter-collapse-button:focus-visible')).toContain('pointer-events: auto')
  expect(css).not.toContain('.purchase-receipt-workspace-form:hover .purchase-receipt-workspace-side .management-filter-collapse-button')
})

it('keeps dashboard activity sidebar sticky and chart surface modern', () => {
  expect(cssRule('.app-content > .dashboard-shell')).toContain('align-items: center')
  expect(cssRule('.app-content > .dashboard-shell')).toContain('padding: var(--space-3)')
  expect(cssRule('.app-content > .dashboard-shell .dashboard-header,\n.app-content > .dashboard-shell .dashboard-grid')).toContain('width: min(100%, 112rem)')
  expect(cssRuleLast('.dashboard-grid')).toContain('align-items: stretch')
  expect(cssRule('.dashboard-side-column')).toContain('position: sticky')
  expect(cssRule('.dashboard-side-column')).toContain('top: var(--space-4)')
  expect(cssRule('.dashboard-side-column')).toContain('height: 100%')
  expect(cssRule('.dashboard-side-column')).toContain('min-height: 0')
  expect(cssRule('.dashboard-side-column')).toContain('overflow: hidden')
  expect(cssRule('.dashboard-side-column')).toContain('contain: layout size')
  expect(cssRule('.dashboard-side-column')).toContain('grid-template-rows: auto minmax(0, 1fr)')
  expect(cssRule('.dashboard-activity-card')).toContain('min-height: 0')
  expect(cssRule('.dashboard-activity-card')).toContain('grid-template-rows: auto minmax(0, 1fr)')
  expect(cssRule('.dashboard-activity-card')).toContain('height: 100%')
  expect(cssRuleLast('.dashboard-activity-card ol')).toContain('min-height: 0')
  expect(cssRuleLast('.dashboard-activity-card ol')).toContain('overflow: auto')
  expect(cssRuleLast('.dashboard-activity-card ol')).toContain('align-content: start')
  expect(cssRuleLast('.dashboard-activity-card ol')).toContain('grid-auto-rows: max-content')
  expect(cssRule('.dashboard-activity-money')).toContain('color: var(--color-text)')
  expect(cssRule('.dashboard-activity-money')).toContain('font-weight: 800')
  expect(cssRule('.dashboard-activity-money')).toContain('white-space: nowrap')
  expect(cssRule('.dashboard-activity-counterparty')).toContain('display: inline')
  expect(cssRule('.dashboard-activity-counterparty')).toContain('margin: 0 0.25em')
  expect(cssRule('.dashboard-activity-counterparty')).toContain('padding: 0')
  expect(cssRule('.dashboard-activity-counterparty')).toContain('color: var(--color-primary)')
  expect(cssRule('.dashboard-activity-document')).toContain('display: inline')
  expect(cssRule('.dashboard-activity-document')).toContain('margin-left: 0.25em')
  expect(cssRule('.dashboard-activity-document')).toContain('padding: 0')
  expect(cssRule('.dashboard-activity-document')).toContain('white-space: nowrap')
  expect(cssRule('.dashboard-activity-document')).toContain('color: var(--color-primary)')
  expect(cssRule('.dashboard-rank-card > header h2')).toContain('font-weight: 800')
  expect(cssRule('.dashboard-rank-card strong')).toContain('color: var(--color-text-muted)')
  expect(cssRule('.dashboard-rank-card strong')).toContain('font-weight: 600')
  expect(cssRule('.dashboard-rank-card em')).toContain('color: color-mix')
  expect(cssRule('.dashboard-rank-card em')).toContain('font-weight: 500')
  expect(cssRuleLast('.dashboard-grid')).toContain('grid-template-columns: minmax(0, 7fr) minmax(16.2rem, 2.7fr)')
  expect(cssRule('.dashboard-kpi-card > header')).toContain('border-bottom: 1px solid var(--color-border)')
  expect(cssRule('.dashboard-kpi-grid')).toContain('grid-template-columns: repeat(3, minmax(0, 1fr))')
  expect(cssRule('.dashboard-kpi-grid article,\n.dashboard-kpi-grid > button')).toContain('grid-template-columns: auto minmax(0, 1fr)')
  expect(cssRule('.dashboard-kpi-grid > button:hover,\n.dashboard-kpi-grid > button:focus-visible,\n.dashboard-kpi-grid > button[aria-pressed=\'true\']')).toContain('background: color-mix')
  expect(cssRule('.dashboard-kpi-grid article:last-child')).toContain('border-right: 0')
  expect(cssRule('.dashboard-kpi-grid svg')).toContain('grid-row: 1 / 4')
  expect(cssRule('.dashboard-kpi-comparison-up svg,\n.dashboard-kpi-comparison-up strong')).toContain('color: var(--color-success)')
  expect(cssRule('.dashboard-kpi-comparison-down svg,\n.dashboard-kpi-comparison-down strong')).toContain('color: var(--color-danger)')
  expect(cssRule('.dashboard-kpi-comparison-flat svg,\n.dashboard-kpi-comparison-flat strong')).toContain('color: var(--color-text-muted)')
  expect(cssRule('.dashboard-period-filter-menu')).toContain('top: calc(100% + 0.35rem)')
  expect(cssRule('.dashboard-period-filter-menu')).toContain('z-index: calc(var(--z-shell) + 6)')
  expect(cssRule('.dashboard-period-filter-menu button:hover,\n.dashboard-period-filter-menu button:focus-visible')).toContain('color: var(--color-primary)')
  expect(cssRule('.dashboard-chart-tabs')).toContain('padding: 0 var(--space-4) 0 calc(var(--space-4) + 1.25rem)')
  expect(cssRule('.dashboard-chart-tabs')).toContain('transform: translateY(-0.25rem)')
  expect(cssRule('.dashboard-column-chart')).toContain('grid-template-columns: 3.25rem minmax(0, 1fr)')
  expect(cssRule('.dashboard-column-chart')).toContain('overflow-x: auto')
  expect(cssRule('.dashboard-column-chart-bars')).toContain('grid-template-columns: repeat(var(--dashboard-day-count, 31), minmax(1.25rem, 1fr))')
  expect(cssRule('.dashboard-column-chart-grid > i')).toContain('background: color-mix')
  expect(cssRule('.dashboard-column-chart-plot b')).toContain('border-radius: 999px 999px var(--radius-xs) var(--radius-xs)')
  expect(cssRule('.dashboard-column-chart-plot b')).toContain('background: linear-gradient(180deg, var(--color-success), var(--color-primary))')
})

it('keeps the cashbook data table in a KV-like layout with project colors', () => {
  expect(cssRule('.finance-cashbook-data-table thead th')).toContain('text-transform: none')
  expect(cssRule('.finance-cashbook-data-table thead th')).toContain('font-size: 0.7rem')
  expect(cssRule('.finance-cashbook-data-table tbody td')).toContain('color: var(--color-text)')
  expect(cssRule('.finance-cashbook-data-table tbody td')).toContain('font-weight: 400')
  expect(cssRule('.finance-cashbook-data-table .management-link-button,\n.finance-cashbook-data-table .finance-cashbook-counterparty-link')).toContain('color: var(--color-text)')
  expect(cssRule('.finance-cashbook-counterparty-link')).toContain('font-weight: 600')
  expect(cssRule('.management-table-viewport > table tbody tr.management-data-row:hover td')).toContain('background: var(--color-surface-muted)')
  expect(cssRule('.finance-cashbook-data-table tbody tr:hover td')).toBe('')
  expect(cssRule('.finance-cashbook-code-link')).toContain('color: var(--color-primary)')
  expect(cssRule('.finance-cashbook-code-link')).toContain('font-weight: 600')
  expect(cssRule('.finance-cashbook-money-column')).toContain('text-align: right')
  expect(cssRule('.finance-cashbook-filter-summary .metric-grid')).toContain('grid-template-columns: 1fr')
  expect(cssRule('.finance-cashbook-filter-summary .metric-grid')).toContain('margin-bottom: var(--space-2)')
  expect(cssRule('.management-kpis .metric-card,\n.finance-cashbook-filter-summary .metric-card')).toContain('display: flex')
  expect(cssRule('.management-kpis .metric-card,\n.finance-cashbook-filter-summary .metric-card')).toContain('background: var(--color-surface)')
  expect(cssRule('.finance-cashbook-star-button')).toContain('background: transparent')
  expect(cssRule('.finance-cashbook-star-button')).toContain('cursor: pointer')
  expect(cssRule('.finance-cashbook-star-button')).toContain('display: inline-flex')
  expect(cssRule('.finance-cashbook-star-button')).toContain('height: 1.5rem')
  expect(cssRule('.finance-cashbook-star-column')).toContain('line-height: 1')
  expect(cssRule('.finance-cashbook-star-button')).toContain('line-height: 1')
  expect(cssRule('.finance-cashbook-checkbox-control')).toContain('display: inline-flex')
  expect(cssRule('.finance-cashbook-checkbox-control')).toContain('width: 1.0625rem')
  expect(cssRule('.finance-cashbook-select-column input[type=\'checkbox\']')).toContain('margin: 0')
  expect(cssRule('.finance-cashbook-select-column input[type=\'checkbox\']')).toContain('width: 0.85rem')
  expect(cssRule('.finance-cashbook-star-column .finance-cashbook-star-button')).toContain('margin: 0 auto')
  expect(cssRule('.finance-cashbook-data-table thead .finance-cashbook-star-button')).toContain('transform: translateY(-1px)')
  expect(cssRule('.finance-cashbook-star-button:hover,\n.finance-cashbook-star-button-active')).toContain('color: var(--color-primary)')
})

it('keeps cashbook detail panel aligned to the KV expanded row structure', () => {
  expect(cssRule('.management-detail-header')).toContain('display: flex')
  expect(cssRule('.management-detail-header')).toContain('justify-content: flex-start')
  expect(cssRule('.management-detail-title-line')).toContain('align-items: center')
  expect(css).toContain('.management-detail-meta-grid-three {\n  grid-template-columns: repeat(3, minmax(0, 1fr));\n}')
  expect(css).toContain('.management-detail-meta-grid-four {\n  grid-template-columns: repeat(4, minmax(0, 1fr));\n}')
  expect(cssRule('.management-detail-meta-span-2')).toContain('grid-column: span 2')
  expect(cssRule('.management-detail-meta-grid > div')).toContain('display: grid')
  expect(cssRule('.management-detail-meta-grid > div')).toContain('grid-template-columns: max-content minmax(0, 1fr)')
  expect(cssRule('.management-detail-meta-grid > div')).toContain('justify-items: start')
  expect(cssRule('.management-detail-meta-grid > div')).toContain('text-align: left')
  expect(cssRule('.management-detail-meta-grid > div')).toContain('border-bottom: 1px solid var(--color-border-muted)')
  expect(cssRule('.management-detail-meta-grid.management-detail-meta-grid-stacked > div')).toContain('grid-template-rows: auto auto')
  expect(cssRule('.management-detail-meta-rows > div')).toContain('display: flex')
  expect(cssRule('.management-detail-meta-rows > div')).toContain('border-bottom: 1px solid var(--color-border-muted)')
  expect(cssRule('.finance-cashbook-linked-documents-inner')).toContain('border: 1px solid var(--color-border-muted)')
  expect(cssRule('.finance-cashbook-detail')).toBe('')
  expect(cssRule('.finance-cashbook-linked-documents-inner')).toContain('padding: var(--space-2)')
  expect(cssRule('.management-record-link')).toContain('display: inline-flex')
  expect(cssRule('.management-record-link')).toContain('min-height: 1.75rem')
  expect(cssRule('.management-record-link')).toContain('padding: 0.25rem 0.375rem')
  expect(cssRule('.management-record-link')).toContain('color: var(--color-info)')
  expect(cssRule('.management-record-link')).toContain('text-decoration: none')
  expect(cssRule('.management-record-link:hover,\n.management-record-link:focus-visible')).toContain('background: color-mix')
  expect(cssRule('.management-record-link:hover,\n.management-record-link:focus-visible')).toContain('text-decoration: none')
  expect(cssRule('.finance-cashbook-linked-document-link')).toContain('color: var(--color-info)')
  expect(cssRule('.finance-cashbook-linked-document-link')).toContain('font-weight: 600')
  expect(cssRule('.finance-cashbook-linked-document-link:hover,\n.finance-cashbook-linked-document-link:focus-visible')).toContain('color: var(--color-info)')
  expect(cssRule('.management-detail-table.management-detail-linked-table')).toContain('width: 100%')
  expect(cssRule('.management-detail-table.management-detail-linked-table')).toContain('min-width: 44rem')
  expect(cssRule('.management-detail-table.management-detail-linked-table')).toContain('table-layout: auto')
  expect(cssRule('.management-detail-linked-table th,\n.management-detail-linked-table td')).toContain('white-space: nowrap')
  expect(cssRule('.management-detail-linked-table th,\n.management-detail-linked-table td')).toContain('text-align: left')
  expect(cssRule('.management-detail-linked-table th:nth-child(2),\n.management-detail-linked-table td:nth-child(2)')).toContain('width: 11rem')
  expect(cssRule('.management-detail-linked-table th:nth-child(n + 3),\n.management-detail-linked-table td:nth-child(n + 3)')).toContain('text-align: right')
  expect(cssRule('.management-detail-footer-actions')).toContain('align-items: center')
  expect(cssRule('.management-detail-footer-actions')).toContain('justify-content: space-between')
  expect(cssRule('.management-detail-footer-actions')).toContain('border-top: 1px solid var(--color-border-muted)')
  expect(cssRule('.management-detail-footer-actions-right')).toContain('justify-content: flex-end')
  expect(cssRule('.management-detail-footer-actions-right')).toContain('margin-left: auto')
  expect(cssRule('.management-detail-footer-actions')).toContain('gap: 0.375rem')
  expect(cssRule('.management-detail-footer-actions .button')).toBe('')
  expect(cssRule('.button')).toContain('display: inline-flex')
  expect(cssRule('.button')).toContain('transition: background-color 160ms ease')
  expect(cssRule('.button')).toContain('white-space: nowrap')
  expect(cssRule('.button-danger')).toContain('background: transparent')
  expect(cssRule('.button-danger')).toContain('color: var(--color-danger)')
})

it('uses shared detail meta typography for labels and values', () => {
  expect(cssRule('.management-detail-meta-label')).toContain('color: var(--color-text-muted)')
  expect(cssRule('.management-detail-meta-label')).toContain('font-size: 0.8rem')
  expect(cssRule('.management-detail-meta-label')).toContain('font-weight: 400')
  expect(cssRule('.management-detail-meta-value')).toContain('color: var(--color-text)')
  expect(cssRule('.management-detail-meta-value')).toContain('font-weight: 700')
  expect(cssRule('.management-detail-meta-grid dt,\n.management-detail-meta-rows dt')).toContain('text-align: left')
  expect(cssRule('.management-detail-meta-grid dd')).toContain('text-align: left')
  expect(cssRule('.management-detail-meta-grid dd')).toContain('white-space: nowrap')
  expect(cssRule('.management-detail-meta-grid.management-detail-meta-grid-stacked dd')).toContain('white-space: normal')
  expect(cssRule('.customer-inline-detail')).toBe('')
  expect(cssRule('.customer-detail-summary')).toBe('')
  expect(cssRule('.customer-detail-summary-main')).toBe('')
  expect(cssRule('.customer-detail-title-line')).toBe('')
  expect(cssRule('.customer-detail-summary-meta')).toBe('')
  expect(cssRule('.customer-detail-tab-panel > dl')).toBe('')
  expect(cssRule('.customer-detail-tab-panel dt')).toBe('')
})

it('keeps shared management table headers sticky and visually distinct', () => {
  const headerRule = cssRule('.management-table-viewport > table > thead th')

  expect(cssRule('.management-list-surface')).toContain('padding: var(--space-1)')
  expect(cssRule('.management-list-surface thead th')).toBe('')
  expect(headerRule).toContain('position: sticky')
  expect(headerRule).toContain('top: 0')
  expect(headerRule).toContain('z-index: 2')
  expect(headerRule).toContain('background: var(--color-surface-muted)')
  expect(headerRule).toContain('color: var(--color-text)')
  expect(headerRule).toContain('box-shadow: inset 0 -1px 0 var(--color-border)')
  expect(headerRule).toContain('font-size: 0.8125rem')
  expect(headerRule).toContain('font-weight: 700')
  expect(headerRule).toContain('text-transform: uppercase')
})

it('shares inline detail tab styling outside customer-only pages', () => {
  const sharedTabBaseSelector =
    '.shell-nav-link,\n.inline-detail-tabs button,\n.dashboard-chart-tabs button'
  const sharedTabActiveSelector =
    ".shell-nav-link[aria-current='page'],\n.inline-detail-tabs button[aria-selected='true'],\n.dashboard-chart-tabs button[aria-selected='true']"

  expect(cssRule('.customer-detail-tabs')).toBe('')
  expect(cssRule('.dashboard-nav')).toBe('')
  expect(css).toContain('.inline-detail-tabs')
  expect(cssRule(sharedTabBaseSelector)).toContain('color: var(--color-text)')
  expect(cssRule(sharedTabBaseSelector)).toContain('font-weight: 600')
  expect(cssRule(sharedTabActiveSelector)).toContain('color: var(--color-primary)')
  expect(cssRule(sharedTabActiveSelector)).toContain('font-weight: 800')
})

it('keeps shared search suggestions aligned with the search box and hoverable like menus', () => {
  const searchRule = cssRule('.management-compact-search')
  const searchFocusRule = cssRule('.management-compact-search:focus-within')
  const leadingRule = cssRule('.management-compact-search-leading')
  const inputRule = cssRule('.management-compact-search input')
  const suggestionsRule = cssRule('.management-search-suggestions')
  const optionRule = cssRule('.management-search-suggestions button')
  const optionHoverRule = cssRule('.management-search-suggestions button:hover,\n.management-search-suggestions button:focus-visible')
  const optionHoverTextRule = cssRule('.management-search-suggestions button:hover span,\n.management-search-suggestions button:focus-visible span')
  const emptyRule = cssRule('.management-search-suggestions-empty')

  expect(searchRule).toContain('border-radius: var(--radius-md)')
  expect(searchRule).toContain('transform: translateX(3px)')
  expect(searchRule).toContain('flex: 0 1 min(33vw, 24rem)')
  expect(searchRule).toContain('width: min(33vw, 24rem)')
  expect(searchRule).toContain('min-width: min(100%, 13rem)')
  expect(searchFocusRule).toContain('z-index: calc(var(--z-shell) + 10)')
  expect(leadingRule).toContain('left: calc(var(--space-4) + 2px)')
  expect(inputRule).toContain('min-height: 2.25rem')
  expect(inputRule).toContain('border-radius: var(--radius-md)')
  expect(inputRule).toContain('padding: 0 2.75rem 0 3rem')
  expect(suggestionsRule).toContain('left: -1px')
  expect(suggestionsRule).toContain('right: -1px')
  expect(suggestionsRule).toContain('z-index: calc(var(--z-shell) + 11)')
  expect(suggestionsRule).toContain('border-radius: var(--radius-md)')
  expect(optionRule).toContain('border: 1px solid transparent')
  expect(optionRule).toContain('padding: 0 var(--space-2)')
  expect(optionRule).toContain('transition:')
  expect(emptyRule).toContain('padding: var(--space-2)')
  expect(optionHoverRule).toContain('border-color: var(--color-primary)')
  expect(optionHoverRule).toContain('background: color-mix(in srgb, var(--color-primary) 14%, var(--color-surface))')
  expect(optionHoverRule).toContain('color: var(--color-primary)')
  expect(optionHoverTextRule).toContain('color: var(--color-primary)')
})

it('keeps inline detail surfaces unframed and summary rows single-line', () => {
  expect(css).toContain('--color-selected-border: var(--color-primary)')
  expect(css).toContain('.management-compact-search:focus-within')
  expect(css).toContain('border-color: var(--color-selected-border)')
  expect(cssRule('.management-data-row-selected td')).toContain('border-top: 1px solid var(--color-selected-border)')
  expect(cssRule('.management-data-row-selected td')).toContain('border-bottom: 1px solid var(--color-selected-border)')
  expect(cssRule('.management-data-row-selected td')).toContain('box-shadow: inset 0 1px 0 var(--color-selected-border)')
  expect(cssRule('.management-detail-row > td')).toContain('border: 0')
  expect(cssRule('.management-detail-row > td')).toContain('background: transparent')
  expect(cssRule('.management-detail-row > td')).toContain('padding: 0')
  expect(cssRule('.management-detail-row-selected > td')).toContain('border-right: 1px solid var(--color-selected-border)')
  expect(cssRule('.management-detail-row-selected > td')).toContain('border-bottom: 1px solid var(--color-selected-border)')
  expect(cssRule('.management-detail-row-selected > td')).toContain('border-left: 1px solid var(--color-selected-border)')
  expect(cssRule('.management-detail-row-selected > td')).toContain('background: transparent')
  expect(cssRule('.management-detail-row-selected > td')).toContain('box-shadow: inset 0 -1px 0 var(--color-selected-border)')
  expect(cssRule('.management-table-viewport > table tbody tr.management-detail-row-selected > td')).toContain('border-bottom: 1px solid var(--color-selected-border)')
  expect(cssRule('.management-inline-detail')).toContain('border: 0')
  expect(cssRule('.management-inline-detail')).toContain('background: transparent')
  expect(cssRule('.management-inline-detail')).toContain('padding: 0')
  expect(cssRule('.management-detail-panel')).toContain('display: grid')
  expect(cssRule('.management-detail-panel')).toContain('gap: var(--space-3)')
  expect(cssRule('.management-detail-panel')).toContain('padding: 0 var(--space-3) var(--space-3)')
  expect(cssRule('.management-detail-panel > section')).toContain('gap: var(--space-3)')
  expect(cssRule('.inline-detail-tabbar')).toContain('border-bottom: 1px solid var(--color-border-muted)')
  expect(cssRule('.inline-detail-tabs')).toContain('display: flex')
  expect(cssRule('.management-detail-summary')).toContain('display: grid')
  expect(cssRule('.management-detail-summary-main')).toContain('min-width: 0')
  expect(cssRule('.management-detail-heading,\n.management-detail-title-line,\n.management-detail-meta-line,\n.management-detail-inline-note')).toContain('display: flex')
  expect(cssRule('.management-detail-meta-line')).toContain('color: var(--color-text-muted)')
  expect(cssRule('.management-detail-meta-line > span + span')).toContain('border-left: 1px solid var(--color-border-muted)')
  expect(cssRule('.management-detail-section')).toContain('display: grid')
  expect(cssRule('.management-detail-header')).toContain('display: flex')
  expect(cssRule('.management-detail-meta-grid')).toContain('grid-template-columns: repeat(auto-fit, minmax(10rem, 1fr))')
  expect(cssRule('.management-detail-meta-rows')).toContain('display: grid')
  expect(cssRule('.management-detail-table')).toContain('width: 100%')
  expect(cssRule('.management-detail-table th')).toContain('background: var(--color-surface-muted)')
  expect(cssRule('.management-detail-table th,\n.management-detail-table td')).toContain('padding: var(--space-2)')
  expect(cssRule('.management-detail-lower')).toContain('display: grid')
  expect(cssRule('.management-detail-lower')).toContain('align-items: stretch')
  expect(cssRule('.management-detail-note')).toContain('border: 1px solid var(--color-border-muted)')
  expect(cssRule('.management-detail-note')).toContain('width: 100%')
  expect(cssRule('.management-detail-note')).toContain('height: 100%')
  expect(cssRule('.management-detail-summary-box')).toContain('display: grid')
  expect(cssRule('.management-detail-summary-box-right')).toContain('grid-column: 1 / -1')
  expect(cssRule('.management-detail-lower-right')).toContain('grid-template-columns: minmax(0, 1fr) max-content')
  expect(cssRule('.management-detail-lower-right')).toContain('column-gap: var(--space-5)')
  expect(cssRule('.management-detail-lower-right .management-detail-note')).toContain('grid-column: 1')
  expect(cssRule('.management-detail-lower-right .management-detail-summary-box-right')).toContain('grid-column: 2')
  expect(cssRule('.management-detail-lower-right .management-detail-summary-box-right')).toContain('grid-template-columns: max-content minmax(5.5rem, max-content)')
  expect(cssRule('.management-detail-lower-right .management-detail-summary-box-right')).toContain('width: max-content')
  expect(cssRule('.management-detail-lines-table,\n.sales-document-lines-table')).toContain('table-layout: auto')
  expect(cssRule('.management-detail-lines-table th:nth-child(1),\n.management-detail-lines-table td:nth-child(1),\n.sales-document-lines-table th:nth-child(1),\n.sales-document-lines-table td:nth-child(1)')).toContain('width: 7rem')
  expect(cssRule('.management-detail-lines-table th:nth-child(2),\n.management-detail-lines-table td:nth-child(2),\n.sales-document-lines-table th:nth-child(2),\n.sales-document-lines-table td:nth-child(2)')).toContain('width: auto')
  expect(cssRule('.management-detail-lines-table th,\n.sales-document-lines-table th')).toContain('white-space: nowrap')
  expect(cssRule('.management-detail-lines-table th:nth-child(n + 3),\n.management-detail-lines-table td:nth-child(n + 3),\n.sales-document-lines-table th:nth-child(n + 3),\n.sales-document-lines-table td:nth-child(n + 3)')).toContain('white-space: nowrap')
  expect(cssRule('.management-detail-summary-box')).toContain('grid-template-columns: 12% 26% repeat(3, 10%) repeat(2, 16%)')
  expect(cssRule('.management-detail-summary-box div')).toContain('display: contents')
  expect(cssRule('.management-detail-summary-box dt')).toContain('grid-column: 1 / 7')
  expect(cssRule('.management-detail-summary-box dd')).toContain('grid-column: 7')
  expect(cssRule('.management-detail-lower-right .management-detail-summary-box-right dd')).toContain('min-width: 5.5rem')
  expect(cssRule('.management-detail-lower-right .management-detail-summary-box-right dd')).toContain('white-space: nowrap')
})
