import { ChevronDown, Edit3, Pin } from 'lucide-react'
import { ManagementFilterGroup } from '../../components/ui-shell/management-layout'
import type { FinanceAccount } from './types'
import type { CashbookFundMode } from './finance-filters'
import { bankAccountDisplayParts, bankAccountDisplayText, bankAccountTriggerText } from './finance-presenter'
interface Props { mode:CashbookFundMode; accountId:string; selectedBankAccount?:FinanceAccount; bankAccounts:FinanceAccount[]; deletedBankAccounts:FinanceAccount[]; pinnedBankAccountIds:string[]; menuOpen:boolean; deletedOpen:boolean; onModeChange:(mode:CashbookFundMode)=>void; onAccountChange:(id:string)=>void; onMenuToggle:()=>void; onDeletedToggle:()=>void; onAdd:()=>void; onEdit:(account:FinanceAccount)=>void; onPin:(id:string)=>void }
export function FinanceFundFilter(p:Props){return <ManagementFilterGroup title="Quỹ tiền">
{([['all','Tổng quỹ'],['cash','Tiền mặt'],['bank','Ngân hàng']] as Array<[CashbookFundMode,string]>).map(([v,l])=><label className={`management-filter-choice${p.mode===v?' management-filter-choice-active':''}`} key={v}><input checked={p.mode===v} name="cashbook-fund" type="radio" onChange={()=>p.onModeChange(v)}/><span>{l}</span></label>)}
{p.mode==='bank'?<div className="management-filter-account-picker"><div className="management-filter-subheading"><span>Tài khoản</span><button type="button" onClick={p.onAdd}>Thêm</button></div><button aria-expanded={p.menuOpen} aria-label="Chọn tài khoản" className="management-filter-account-trigger" type="button" onClick={p.onMenuToggle}><span>{p.selectedBankAccount?bankAccountTriggerText(p.selectedBankAccount):'Chọn tài khoản'}</span><ChevronDown aria-hidden="true" size={16}/></button>{p.menuOpen?<div className="management-filter-account-menu" role="listbox" aria-label="Danh sách tài khoản ngân hàng"><div className="management-filter-account-list">{p.bankAccounts.length?p.bankAccounts.map(a=><AccountOption account={a} key={a.id} selected={p.accountId===a.id} pinned={p.pinnedBankAccountIds.includes(a.id)} onChoose={p.onAccountChange} onEdit={p.onEdit} onPin={p.onPin}/>):<span className="management-filter-account-empty">Không có tài khoản phù hợp</span>}</div>{p.deletedBankAccounts.length?<div className="management-filter-account-deleted"><button aria-expanded={p.deletedOpen} className="management-filter-account-deleted-toggle" type="button" onClick={p.onDeletedToggle}><span>Tài khoản đã xóa</span><ChevronDown aria-hidden="true" size={14}/></button>{p.deletedOpen?<div className="management-filter-account-list">{p.deletedBankAccounts.map(a=><DeletedAccount account={a} key={a.id}/>)}</div>:null}</div>:null}</div>:null}</div>:null}
</ManagementFilterGroup>}
function AccountOption({account,selected,pinned,onChoose,onEdit,onPin}:{account:FinanceAccount;selected:boolean;pinned:boolean;onChoose:(id:string)=>void;onEdit:(a:FinanceAccount)=>void;onPin:(id:string)=>void}){const label=bankAccountDisplayText(account);return <div aria-selected={selected} className="management-filter-account-option" role="option" tabIndex={0} onClick={()=>onChoose(account.id)} onKeyDown={e=>{if(e.key!=='Enter'&&e.key!==' ')return;e.preventDefault();onChoose(account.id)}}><AccountLabel account={account}/><span className="management-filter-account-actions"><button aria-label={`Sửa tài khoản ${label}`} className="management-icon-button" type="button" onClick={e=>{e.stopPropagation();onEdit(account)}}><Edit3 aria-hidden="true" size={15}/></button><button aria-label={`Ghim tài khoản ${label}`} aria-pressed={pinned} className={pinned?'management-icon-button management-filter-account-action-pinned':'management-icon-button'} type="button" onClick={e=>{e.stopPropagation();onPin(account.id)}}><Pin aria-hidden="true" size={15}/></button></span></div>}
function AccountLabel({account}:{account:FinanceAccount}){const p=bankAccountDisplayParts(account);return <span className="management-filter-account-option-label"><strong>{p.primary}</strong>{p.secondary?<span>{p.secondary}</span>:null}{p.tertiary?<em>{p.tertiary}</em>:null}</span>}
function DeletedAccount({account}:{account:FinanceAccount}){return <div className="management-filter-account-option management-filter-account-option-muted"><AccountLabel account={account}/><span className="status-chip status-chip-neutral">Đã xóa</span></div>}
